name: Maven Build - Java 17
run-name: Java CI on ${{ github.ref}} by ${{ github.actor }}
on: [push]
jobs:
  Maven-Build:
    # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64
          cache: 'maven'
      - name: Build with Maven
#        run: mvn -B package --file pom.xml
        run: mvn -B --update-snapshots verify --file pom.xml
